baseurl = "https://naone.netlify.com/"
title = "Naone"
theme = "pargo"

googleAnalytics = ""
disqusShortname = "blognawar"

[permalinks]
  post = "/blog/:slug/"
  page = "/:slug/"

[params]
    # Site Author
    author = ""

    # Description/subtitle for homepage
    description = "Hello, Blog ini belum jadi. Sabar ya..."


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    wight = 1
  [[menu.main]]
    identifier = "works"
    name = "Works"
    url = "/works/"
    wight = 2
  [[menu.main]]
    identifier = "tools"
    name = "Tools"
    url = "/tools/"
    wight = 3
