baseurl = "https://www.myweb.com"
title = "Naone"
theme = "pargo"

googleAnalytics = ""
disqusShortname = "blognawar"

[permalinks]
  post = "/blog/:slug/"
  page = "/:slug/"

[params]
    # Site Author
    author = ""

    # Description/subtitle for homepage
    description = "Hello, Blog ini belum jadi. Sabar ya..."


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    wight = 1
  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "https://deviantart.com/"
    wight = 2
  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com"
    wight = 3
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com"
    wight = 4
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "http://feeds.feedburner.com/"
    wight = 5
